### ISSUE TITLE
Separate main.cpp into header and cpp files

### ISSUE THREAD

**Issue by Terrence1005** [Terrence1005/Finite-State-Machine#3]
The NFA class should be separated into one header files (with the respective implementation in a cpp file).

The methods can be in another .hpp and .cpp files (maybe NFA_Translator.hpp and NFA_Translator.cpp).

**Comment by rnbez** [comment]
Task completed in the commit b32b96752bf5c3b5fe51a28a42a7e0557dc7a0e5
